apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-mini.fullname" . }}
  labels:
    app: {{ .Values.appName }}
    {{- include "hello-mini.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appName }}
    {{- include "hello-mini.selectorLabels" . | nindent 4 }}
